language: csharp
solution: Craft_dish.sln
install:
- nuget restore Craft_disht.sln
- nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
- ls -R testrunner
- msbuild /p:Configuration=Debug Craft_dish.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./UI_test/bin/Debug/UItest.dll