version: 1.0.{build}
image: Visual Studio 2019

environment:
  keystore-password:
    secure: 1234-qwer # YourPassword for keystore

before_build:
  - nuget restore
build_script:
#  - msbuild "/t:SignAndroidPackage" "/p:Configuration=Release" "Craft_dish\Craft_dish.csproj"
  - msbuild /verbosity:quiet "/t:SignAndroidPackage" "/p:Configuration=Release" "/p:AndroidKeyStore=true" "/p:AndroidSigningKeyAlias=craftdishkey" "/p:AndroidSigningKeyPass=%keystore-password%" "/p:AndroidSigningKeyStore=craftdishkey.keystore" "/p:AndroidSigningStorePass=%keystore-password%"  "Craft_dish\Craft_dish.csproj"
 # - msbuild "/t:SignAndroidPackage" "/p:Configuration=Release" "/p:AndroidKeyStore=true" "/p:AndroidSigningKeyAlias=%keystore-password%" "/p:AndroidSigningKeyPass=%keystore-password%" "/p:AndroidSigningKeyStore=%keystore-password%" "/p:AndroidSigningStorePass=%keystore-password%"  "Craft_dish\Craft_dish.csproj"
artifacts:
  - path: Craft_dish\bin\Release\Craft_dish.Craft_dish-Signed.apk
 
notifications:
- provider: Email
  to:
  - fiodarmotin@gmail.com
  - ordeh@mail.ru
  subject: 'Build {{status}}: {{projectName}} {{buildVersion}}'
  message: Build was finished
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false 